### ISSUE TITLE
windos系统发现问题麻烦向您请教下.

### ISSUE THREAD

**Issue by victoryGithup** [Blackn-L/day-day-account-book-frontend#1]
/** 软件VScode 和 WS . 问题如下 windows10系统   vant一直引用不到 试了很久也是不可以. 特向您请教下. 十分感谢 ~*/

下午5:24:07 [vite] Internal server error: Failed to resolve import "D:/node_modules/vant/es/button/style" from "src\main.js". Does the file exist?
  Plugin: vite:import-analysis
  File: D:/WEBWorkspace/day-day-account-book-frontend/src/main.js
  35 |    Lazyload,
  36 |  } from "vant";
  37 |  import 'D:/node_modules/vant/es/button/style';
     |                                             ^
  38 |  import 'D:/node_modules/vant/es/icon/style';
  39 |  import 'D:/node_modules/vant/es/nav-bar/style';
      at formatError (D:\WEBWorkspace\day-day-account-book-frontend\node_modules\vite\dist\node\chunks\dep-4b9dfa16.js:36769:46)
      at TransformContext.error (D:\WEBWorkspace\day-day-account-book-frontend\node_modules\vite\dist\node\chunks\dep-4b9dfa16.js:36765:19)
      at normalizeUrl (D:\WEBWorkspace\day-day-account-book-frontend\node_modules\vite\dist\node\chunks\dep-4b9dfa16.js:73682:26)
      at async TransformContext.transform (D:\WEBWorkspace\day-day-account-book-frontend\node_modules\vite\dist\node\chunks\dep-4b9dfa16.js:73822:57)
      at async Object.transform (D:\WEBWorkspace\day-day-account-book-frontend\node_modules\vite\dist\node\chunks\dep-4b9dfa16.js:36985:30)
      at async doTransform (D:\WEBWorkspace\day-day-account-book-frontend\node_modules\vite\dist\node\chunks\dep-4b9dfa16.js:52049:29)

**Comment by Blackn-L** [comment]
不好意思，刚看到，这个是 vite-plugin-style-import 导致的一个 Bug
解决办法：
vite.config.js中
把
resolveStyle: (name) => `vant/es/${name}/style` 
改为
resolveStyle: (name) => `/node_modules/vant/es/${name}/style`
21 年12 月的代码中已提交修复了
相关 Issues https://github.com/vbenjs/vite-plugin-style-import/issues/52

**Comment by victoryGithup** [comment]
HI 。 。 。 。 。 。 
 您 的 信 件 我 已 经 收 到了哦！感谢您的来信。祝您生活愉快 ！
